### ISSUE TITLE
Thank you & link

### ISSUE THREAD

**Issue by omkisker-su** [Impyy/ptpwn#1]
Not really an issue- just wanted to thank you so much for creating this. Worked perfectly. One suggestion- it took me forever to find the right version of packet tracer... Maybe include this link (https://onlinenetworkssolution.blogspot.com/2016/07/download-cisco-packet-tracer.html) in the README so others can download it quicker? Thank you again, could not have passed my class without you.

**Comment by Impyy** [comment]
Good idea, thanks. I added two links to the README, but I couldn't find an official one for 6.2.

**Comment by Impyy** [comment]
Actually, nevermind, those won't work as they will expire after a while.

**Comment by Impyy** [comment]
I added a link to the packet tracer download page instead
